server:
  port: 8080
  servlet:
    context-path: /xf_mall
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/xf_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
<<<<<<< HEAD
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
=======
      hibernate:
        ddl-auto: update
      show-sql: true
  thymeleaf:
    cache: false
>>>>>>> b77616cf504c907cb9edd662d58a1ad86e2e484c
