spring:
  profiles:
    active: prod

  mail:
        default-encoding: utf-8
        host: smtp.126.com
        #发送者的邮箱密码
        password: 123456huyaxing
        #端口
        port: 25
        #协议
        protocol: smtp
        #发送者的邮箱账号
        username: huystar@126.com
  server:
      port: 8081
sdk:
 alipay:
  dev: true #默认false,为true表示使用沙箱环境
  sign-type: RSA2 #签名算法
  app-id: 2016091600523365 #应用ID
  private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCqsgUiRWr/IHJHLN0JCRr2gLrH7FXCR4SzMKJ5mCbrB2g4/m/cqGuZrIp4Bo4JDqJ5dvfOw9kkRAI+nHRsyeeGbD0maF7SieIIyTnt2MKnrsuyLmOuoPee6/h1CgYbfqHQneQ2jSgRiPI16NnknKh2haDP/L3WalOgaNxoxQ5QVSTgGTiW21ZN9rpgCOq7d9hAy19mg2IUVxGbLKk4choQzEmIYTwgy7bty8twawhT3Jn/cvKC8BzHMVQO9n/LbTlI83Kmsjy4huzXNlromc4p+47+Jf9gEmNLi1otDijcZNYFV46+e9j8l4XYq8zlhGzOCL37KhAz6eZ6pqi7wVM5AgMBAAECggEBAICrtQcCgQdUdBCHFw+Kl5Kdsy6lTngm5TcWQEOcmCmu6becxMH3CzVKRQ75EfRt3bfmICLyqyqVQYPk+DZRdH919BqRrnjSi1rIJSzPqtwv/UiRg37NxBs+EYpYRgZPzLavbqpYeY3OR5avsiCMnsjJLlHaWVfZyrQul4c6k/GlIWucnhe5HeCOE5ih/2PMc6Y09h0pYlb1Kusrjt0gqsHO7qF+omWIEGpnlBn2c0jff+7eE+d4hE1rpWNeocnQiZs7mSTgdxd2hy1e+U8jyjg/3F4yr5iCb5o+e4SCdIO2Qo3hMLgaepVaHsK/cH3euFRlkUHNYhKp3BHz6decXQECgYEA3igH6jXtwGQoCXICzJdGvjp9REgDR3PwUkmmfzNlcv6J+BIkIDOrF6bPDGdVYmQD33lT9cG1qApNrCgDb5iuvdrAlPEleogmInkZEu+EHaAQAIzbcBaoUdsTsQxbXZ/sd0nEjMR+NZdosstBxK4i5ishFMTX6TBOW4JXjyH2WlECgYEAxLMKd61dxwef7Z4OyCm/aXX+h6OzVeq+mmvIq2EILQ3V03m25X5yybHMWA0fpz8LOlyCfNW53yJvgLtD6rWg9U/OKv2fbz8jaW8hlspOd3bZnPudDCflqwTrlSwGvzk45lrMBu8k1MfFhAXTpQwYRcCRLPOgJExqKkkd50P3yGkCgYEA0t8spCSMiRKI7m5KOelePTNHtIimlCx48aL3Z8ZhhcYXMGIH6Iki3lB4OE3dvocxJe8Ew0IcLGWbVM6mdEd5lr0OEFLWQHj7ub05D8BKp9RHXD5YDQ10uD47ctNH5pbm3lQnPXdGVZhiyVQmGYsxlUlbHVu7lp1Dw5j1g+e48AECgYEAprpYcg8KwUzuO9zRDMuOSxdQM6sHtRjwjTY1d0cdRgtHJyUxaZ/gLqS94Bjnrr0aiFKn7KbBEak/uG+DZyyjjawixoAKp6JuIs2nPAipsEuWs6D3grlCzM6z3dLeuTII0AFAldQZdR8MhhbmSi1RWbabl+293WbESqmFZmVPX5kCgYARdBW+Sv4ucxwGnF188HpUaKoINhGUgK6kadqlH7qsALzrUaBbA9poTLgEzgdB2bOtgqFtBIkma4ygChRM5gTvBjZKdM27UdpQEF7y+TviiY8AMKiK43fa/jPN9UmXfVgAZpRJPfbdQU3Lrvdy54l1T0R5d4mIR9GmwVnITrQz0A==
   #应用私钥
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsyNZTYoS8C33zULSIvFMGTUiD/QPZRKt4aH0CttbHR47usPZFujSm8wgEZunn+SqPLQVbJYBi9ucVvjDm7HiezGtYtXgHF19QAdiUJH47Olz4v4/yKZVFFvEqlM4mKljkyiLzsqH2P7X5BNIIFF7s2iXamZU3w06chcOaB+4Sz1GBsJ7637YwTgZppaLwXx0siUkHKrAwOETLo/23xGjfoAP5bP67OukDODMt+52U/BEiFmZ2kLxeuc7rYpm0rBvMLMB15vo87CdMqHLCav6nb8iHj96p3yrj+1ZCC/sMK9KUjyfJxMEFvTQf54ZMJKO12H3JMbKwkLyZNqPnAcnLQIDAQAB
   #支付宝公钥
